# -*- coding: utf-8 -*-
"""1.linear-regression-single-variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QakiOVkdwN3xlwvzFqNA8zB8mACDfrT6

linear regression with one variable :

predicting home price in monroe, new jersey(USA) based on square feet area
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv('https://raw.githubusercontent.com/risitadas/machine-learning-in-python/main/homeprices-csv.csv?token=GHSAT0AAAAAABZSLHWIDRIYUUUVIC6LJLDWYZ5UMWA')
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area(sqr ft)')
plt.ylabel('price(US$)')
plt.scatter(df.area, df.price, color = 'green', marker = '+')

# creating Linear Regression object
  reg = linear_model.LinearRegression()
  reg.fit(df[['area']],df.price)

"""1. predicting price of a home with area = 3300 sqr ft"""

reg.predict([[3300]])

reg.coef_

reg.intercept_

"""Y = m * X + b (m is coefficient and b is intercept)"""

135.78767123 * 3300 + 180616.43835616432

"""2. predicting price of a home with area = 5000 sqr ft"""

reg.predict([[5000]])

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area' , fontsize = 20)
plt.ylabel('price' , fontsize = 20)
plt.scatter(df.area, df.price , color = 'red' , marker = '+')
plt.plot(df.area , reg.predict(df[['area']]) , color = 'blue')

"""generating CSV file with list of home price predictions"""

area_df = pd.read_csv('https://raw.githubusercontent.com/risitadas/machine-learning-in-python/main/areas-csv.csv?token=GHSAT0AAAAAABZSLHWJJRJ4EMZ7QAKJX3W2YZ5W3NA')
area_df

p = reg.predict(area_df)
p

area_df['prices'] = p
area_df

area_df.to_csv("https://raw.githubusercontent.com/risitadas/machine-learning-in-python/main/prediction-csv.csv?token=GHSAT0AAAAAABZSLHWJDHPFMTKTIITAJ7XYYZ5XHTQ", index = False)
area_df